# Generated by Django 2.1.2 on 2018-11-07 08:56

import cfp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('talk', 'A talk (25 minutes)'), ('workshop', 'A workshop (3 hours)'), ('poster', 'A poster'), ('kids-workshop', 'An Education Summit workshop for young coders (Saturday, 50 mins)'), ('teachers-workshop', 'An Education Summit workshop for educators (Sunday, 50 mins)'), ('teachers-talk', 'An Education Summit talk for educators (Sunday, 25 mins)'), ('other', 'Something else')], max_length=40)),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('copresenter_names', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('description_private', models.TextField(blank=True, validators=[cfp.validators.max_300_words])),
                ('outline', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('aimed_at_new_programmers', models.BooleanField()),
                ('aimed_at_teachers', models.BooleanField()),
                ('aimed_at_data_scientists', models.BooleanField()),
                ('would_like_mentor', models.BooleanField()),
                ('would_like_longer_slot', models.BooleanField()),
                ('state', models.CharField(blank=True, choices=[('confirm', 'Confirmed'), ('cancel', 'Cancelled'), ('accept', 'Accepted'), ('reject', 'Plan to Reject'), ('withdrawn', 'Withdrawn'), ('placeholder', 'Schedule Placeholder')], max_length=40)),
                ('track', models.CharField(blank=True, max_length=40)),
                ('special_reply_required', models.BooleanField(default=False)),
                ('scheduled_room', models.CharField(blank=True, max_length=40)),
                ('scheduled_time', models.DateTimeField(null=True)),
                ('coc_conformity', models.BooleanField()),
                ('ticket', models.BooleanField()),
                ('confirmed', models.DateTimeField(null=True)),
                ('replied_to', models.DateTimeField(null=True)),
                ('break_event', models.BooleanField(default=False)),
                ('conference_event', models.BooleanField(default=False)),
                ('length_override', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
